apiVersion: v1
kind: Service
metadata:
  labels:
    app: movies-abishar
  name: movies-abishar-svc
  namespace: movies-abishar
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: movies-abishar
  sessionAffinity: None
  type: ClusterIP
